### ISSUE TITLE
Submit a Poll Response

### ISSUE THREAD

**Issue by mihayounas** [mihayounas/My-First-Agile-Project#3]
In order to **give my opinion** as a **user**, I can **select and submit answer from the poll**

**Comment by mihayounas** [comment]
In order to **provide anonymous feedback** as a **user**, I can **hide my identity in poll response**.

## Acceptance Criteria:

- The option should be as a checkbox
- The checkbox should be checked as default
- This option should appear next to submit button

## Tasks

- [ ] Include checkbox by styling the view with HTML and CSS
- [ ] Do not include username
- [ ] Test functionality

**Comment by mihayounas** [comment]
In order to **provide additional thoughts** as a **user**, I can **add a comment before I submit my poll response**.

## Acceptance Criteria

-This option should have text space for extra comments
-  Font size of 10
- After submitting this comment should be added and displayed

##Tasks

- [ ] Add comment to the view and style it
