### ISSUE TITLE
Publish a Poll

### ISSUE THREAD

**Issue by mihayounas** [mihayounas/My-First-Agile-Project#4]
In order to **collect users feedbacks** as a **administrator**, I can **publish a poll**

**Comment by mihayounas** [comment]
In order to **automatically hide the poll** as a **administrator**, I can **pick the expiry date while publishing the poll**

## Acceptance Criteria:

- The poll should disappear at 11.59 PM on the selected date
- Expiry date should be at least 3 days after the current date

## Tasks

- [ ] Update Admin view to include date picker
- [ ] Create function in javascript to vaidate expiry date
- [ ] update the controller function
- [ ] Update unit test scripts
- [ ] Test functionality
